const articles = [
    {
        articleURL: 'learn-react',
        title: 'The Fastest Way to Learn React',
        content: [
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `         
        ]
    },
    {
        articleURL: 'learn-java',
        title: 'The Fastest Way to Learn Java',
        content: [
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `,
            `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Porttitor lacus luctus accumsan tortor posuere ac. Iaculis eu non diam phasellus vestibulum. Ipsum dolor sit amet consectetur. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Neque vitae tempus quam pellentesque nec nam aliquam. Tellus in hac habitasse platea dictumst. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Nullam vehicula ipsum a arcu cursus vitae congue mauris. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Urna neque viverra justo nec. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Nisl vel pretium lectus quam id leo in vitae turpis. Placerat duis ultricies lacus sed turpis tincidunt. Non odio euismod lacinia at quis risus sed vulputate. Nibh mauris cursus mattis molestie a iaculis at. Id porta nibh venenatis cras sed felis eget.
            `         
        ]
    },
];

export default articles;